"""Add fake_column to Comment

Revision ID: 1a50d24cfff7
Revises: 687e76a21fd6
Create Date: 2025-04-18 00:02:10.054290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a50d24cfff7'
down_revision: Union[str, None] = '687e76a21fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('fake_column', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'fake_column')
    # ### end Alembic commands ###
